version: 2
jobs:
  build:
    docker:
    - image: ishakhsuvarov/axp-connector-testing:0.9

    working_directory: ~/repo

    steps:
    - run: 
        name: Building Magento 2.3-develop
        command: |
          git clone https://github.com/magento/magento2.git --depth 1 --single-branch --branch 2.3-develop .
          mkdir axp-connector

    - checkout:
        path: axp-connector
     
    - restore_cache:
        keys:
          - magento-dependencies-{{ checksum "composer.lock" }}

    - run:
        name: Installing dependencies
        command: composer install -n
        
      - save_cache:
          key: magento-dependencies-{{ checksum "composer.lock" }}
          paths:
            - "vendor"
    
    - run:
        name: Installing axp-connector
        command: |
            composer config minimum-stability dev
            composer config repositories.meta path ./axp-connector
            composer config repositories.modules path ./axp-connector/*/*
            composer require adobe/axp-connector

    - run:
        name: Unit Test
        command: ./vendor/phpunit/phpunit/phpunit -c dev/tests/unit
