version: 2
jobs:
  build:
    docker:
    - image: circleci/php:7.1

    working_directory: ~/repo

    steps:
    - run: sudo apt-get -y update && sudo apt-get install -y libpng-dev libxml2-dev libxslt1-dev
    - run: sudo docker-php-ext-install bcmath
    - run: sudo docker-php-ext-install gd
    - run: sudo docker-php-ext-install soap
    - run: sudo docker-php-ext-install xsl
    - run: sudo docker-php-ext-install pdo_mysql
    - run: git clone https://github.com/magento/magento2.git --depth 1 --single-branch --branch 2.3-develop .
    - run: mkdir axp-connector
    - checkout:
        path: axp-connector

    - run: composer install -n
    - run: composer config minimum-stability dev
    - run: composer config repositories.meta path ./axp-connector
    - run: composer config repositories.modules path ./axp-connector/*/*
    - run: composer require adobe/axp-connector

    - run: phpunit -c dev/tests/unit
