version: 2
jobs:
  build:
    docker:
    - image: ishakhsuvarov/axp-connector-testing:0.9

    working_directory: ~/repo

    steps:
    - run: git clone https://github.com/magento/magento2.git --depth 1 --single-branch --branch 2.3-develop .
    - run: mkdir axp-connector
    - checkout:
        path: axp-connector

    - run: composer install -n
    - run: composer config minimum-stability dev
    - run: composer config repositories.meta path ./axp-connector
    - run: composer config repositories.modules path ./axp-connector/*/*
    - run: composer require adobe/axp-connector

    - run: ./vendor/phpunit/phpunit/phpunit -c dev/tests/unit
